### PR TITLE
Closes #21

### LINKED ISSUE #21: Add user creation functionality to the server
The following is only an attempt to keep track of related open issues. It doesn't represent all what needs to be done
- [x] Create `User` model. Closes #15  
- [x] Add `/register` route. Closes #16 

child to #5

### PR DESCRIPTION
**Pull request by jidemobell**
1. created  user model
   
2. add a createUser function in /server/src/controllers with password hashing using bcrypt

3.  create a routes folder/server/src/routes to contain routes code for each model and import first user route to /src/routes.js

4. add environment variables to src/config/config.js

5. update server log with tracer and connected server to mongodb with mongoose connect

### CODE REVIEW

**Comment by peoray** [comment]
I have always favoured using `.env` for storing keys and other secrets we want to hide.
Looks better and cleaner to me, also, we can have an `env.example` file for others to know what keys they would need to make the app work well

**Review by peoray — COMMENTED** [review]
We don't need body parser, in express 4.x.x, you can do `express.json`

**Comment by peoray** [comment]
I tried running the app, it wasn't working

**Review by peoray — COMMENTED** [review]
Is the `register` route suppose to a `GET` request or a `POST`? I was thinking `POST`

**Comment by jidemobell** [comment]
sure we can move into env
i had to change the port to something other than 8081

**Review by peoray — COMMENTED** [review]
Looks good to me. 

How do you handle the validation?

**Review by peoray — COMMENTED** [review]
Can i suggest we move the mongo logic to a separate config file,
let's keep `app.js` super slim

**Comment by ghost** [comment]
Thanks for your hard work :tada: 

## Here are some workflow things to fix:
- Don't forget to commit package-lock.json whenever you commit package.json (this will also avoid commmit duplication, like *install bcrypt*).
- Squash npm install commits with the commit where you first used it.
- Also squash edits to your own work (e.g add user model and update user model commits). You can also use `git commit --amend` if you forgot to add something to your last commit.

Tip: You can alter the branch's history since it'll be deleted after merge, and you're the only one using it.

## Here are some architectural things to improve:
- Define the schema and then use `module.exports = mongoose.model('User', UserSchema)`. The string argument will be the name of the model. That way, the model will be separate from the controller (MVC architecture).
- This is related to the first bullet: You can use middleware (mongoose hooks) for hashing instead of promises and you won't need to manually do `password: hash` (Check Schema.pre on 'save' in mongoose docs).
- Better have a `/register` endpoint than a `/user/register`, since endpoints are not tied to models.
- router vs app: Router was designed to be used on large applications that are separated in multiple modules (modular mountable route handlers), in our case it's not needed.
- routes: You should move the logic to a controller or/and a policy (stuff like validation goes here) instead of having controllers, routes and policies in 1 file.
- All configuration should go to config.js to be easy to modify. Use `config.optionalGroupingObjectName.propertyName` instead of manually inserting `process.env` or a string in different places.
- regarding `config/config.js`: It must be exported via module.exports to be used, otherwise the configuration there will not matter.
 
### Naming conventions:
Should we rename `users.js` -> `AuthenticationController.js` ?

## Some things I didn't understand:
- What did [edit port](https://github.com/chingu-voyage7/Bears-Team-04/pull/24/commits/f34503e5ae0e3f3005f96e3b32b2f6abd1096f19) do ?
- What is the difference between `development` and `test` env ?

**Comment by jidemobell** [comment]
* Define the schema and then use module.exports = mongoose.model('User', UserSchema). The string argument will be the name of the model. That way, the model will be separate from the controller (MVC architecture).
***

```
const User = mongoose.model('User', UserSchema)
module.exports = User
```

squashing the two lines above is the same as what is in the first point


* Better have a /register endpoint than a /user/register, since endpoints are not tied to models.
***
i was thinking a modular approach for more structure presentation, of course, some endpoint wouldn't be attached to models. However, for a small sized app as this, we may not need such endpoint altogether.


* routes: You should move the logic to a controller or/and a policy (stuff like validation goes here) instead of having controllers, routes, and policies in 1 file.
***
I saw the chat with @peoray  on policies and it does make sense (structure wise), will review as suggested



* All configuration should go to config.js to be easy to modify. Use config.optionalGroupingObjectName.propertyName instead of manually inserting process.env or a string in different places.
***

corrected

* Should we rename users.js -> AuthenticationController.js ?
absolutely
***


* What is the difference between development and test env ?

I do run test on a different DB especially when working with an app that requires data seeding, probably not needed here

**Comment by jidemobell** [comment]
about workflow
***

The last time I worked on a project with a team, it was a rule that we have a statement for every commit. I guess they wanted to track every little thing we did at every commit. A bit of work really, but I picked that up from there. I will adjust that

**Review by ghost — APPROVED** [review]
The history is in a good enough state for the project, we can proceed like this.

**Comment by ghost** [comment]
I'll proceed with the merge since peoray won't be on for the upcoming 2 days

**Pull request merged**
